% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={group14wyw},
  pdfauthor={me},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{group14wyw}
\author{me}
\date{2023-03-13}

\begin{document}
\maketitle

\hypertarget{glm-part-1}{%
\section{GLM Part 1}\label{glm-part-1}}

In this part, we read dataset14.csv, and cleansing was performed on the
data. For instance, deleting rows with null values and converting A and
B to 0 and 1

~

\hypertarget{correlation-analysing}{%
\subsection{correlation analysing}\label{correlation-analysing}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggpairs}\NormalTok{(coffee\_glm[,}\DecValTok{2}\SpecialCharTok{:}\DecValTok{8}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{group14wyw_files/figure-latex/unnamed-chunk-1-1} 

}

\caption{\label{fig:scat} correlation between each variables}\label{fig:unnamed-chunk-1}
\end{figure}

Figure 1 shows there is strong correlation between the first three
variables: aroma, flavor and acidity. In addition, aroma, flavor and
acidity have medium correlation with QualityClass, category is in weak
correlation. However, the correlation of the last two cariables are
strongly weak.

The strong correlation shows that we need to do further data cleaning.
First, seperating the dataset into two catagories, one callled
coffee\_cor, the other one is coffee\_non\_cor.

\hypertarget{model-1-the-first-three-variables-with-principal-component-analysis-and-3-variables.}{%
\subsection{model 1 : The first three variables with principal component
analysis and 3
variables.}\label{model-1-the-first-three-variables-with-principal-component-analysis-and-3-variables.}}

We performed a principal components analysis on coffee1\_1.

\begin{verbatim}
## Importance of components:
##                           Comp.1    Comp.2     Comp.3
## Standard deviation     1.6198441 0.4944852 0.36275257
## Proportion of Variance 0.8746317 0.0815052 0.04386314
## Cumulative Proportion  0.8746317 0.9561369 1.00000000
\end{verbatim}

As we can see from the table above, the cumulative proportion of the
first component is 0.8746, so we can only choose the first component.

~

Trying: 1st glm function

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{verbatim}
## 
## Call:
## glm(formula = Qualityclass ~ PC1 + category_two_defects + altitude_mean_meters + 
##     harvested, family = binomial(link = "cloglog"), data = final_1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7770  -0.4827  -0.0138   0.2034   3.7660  
## 
## Coefficients:
##                        Estimate Std. Error z value Pr(>|z|)    
## (Intercept)           7.437e+01  7.789e+01   0.955    0.340    
## PC1                  -4.237e+00  2.833e-01 -14.955   <2e-16 ***
## category_two_defects -7.312e-03  1.787e-02  -0.409    0.682    
## altitude_mean_meters  6.180e-06  7.953e-06   0.777    0.437    
## harvested            -3.712e-02  3.868e-02  -0.960    0.337    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1283.4  on 925  degrees of freedom
## Residual deviance:  533.6  on 921  degrees of freedom
## AIC: 543.6
## 
## Number of Fisher Scoring iterations: 9
\end{verbatim}

~

\hypertarget{model-2-all-variables-with-principal-component-analysis.}{%
\subsection{model 2 : All variables with principal component
analysis.}\label{model-2-all-variables-with-principal-component-analysis.}}

We performed a principal components analysis on coffee1\_3.

\begin{verbatim}
## Importance of components:
##                          Comp.1    Comp.2    Comp.3    Comp.4     Comp.5
## Standard deviation     1.749350 1.0734284 0.9976865 0.9042951 0.77722534
## Proportion of Variance 0.437175 0.1646069 0.1421969 0.1168214 0.08629703
## Cumulative Proportion  0.437175 0.6017819 0.7439788 0.8608002 0.94709722
##                            Comp.6     Comp.7
## Standard deviation     0.49245507 0.35750169
## Proportion of Variance 0.03464457 0.01825821
## Cumulative Proportion  0.98174179 1.00000000
\end{verbatim}

As we can see from the table above, the cumulative proportion of the
fourth component is 0.8608002, so we can only choose the first four
component.

Trying: 2st glm function

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{verbatim}
## 
## Call:
## glm(formula = V5 ~ RC1 + RC2 + RC4 + RC3, family = binomial(link = "logit"), 
##     data = final_2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3701  -0.4274  -0.0028   0.3495   4.3489  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  0.18990    0.11127   1.707   0.0879 .  
## RC1         -6.07330    0.42747 -14.208   <2e-16 ***
## RC2         -0.14806    0.10444  -1.418   0.1563    
## RC4         -0.10265    0.14475  -0.709   0.4782    
## RC3          0.06929    0.14167   0.489   0.6248    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1283.43  on 925  degrees of freedom
## Residual deviance:  545.25  on 921  degrees of freedom
## AIC: 555.25
## 
## Number of Fisher Scoring iterations: 7
\end{verbatim}

All of these two models do not fit well, and the correlation figure
shows that the last three variables have really weak relationship with
QualityClass, so in this model, we try to fit the third model by
deleting harvested, category and altitude.

~

\hypertarget{model-3-first-3-variables-with-principal-component-analysis.}{%
\subsection{model 3 : First 3 variables with principal component
analysis.}\label{model-3-first-3-variables-with-principal-component-analysis.}}

\begin{verbatim}
## Importance of components:
##                           Comp.1    Comp.2     Comp.3
## Standard deviation     1.6198441 0.4944852 0.36275257
## Proportion of Variance 0.8746317 0.0815052 0.04386314
## Cumulative Proportion  0.8746317 0.9561369 1.00000000
\end{verbatim}

As we can see from the table above, the cumulative proportion of the
second component is 0.9561369, so we can only choose the first two
components.

Trying: 3rd glm function

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{verbatim}
## 
## Call:
## glm(formula = V3 ~ RC1 + RC2, family = binomial(link = "logit"), 
##     data = final_3)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2960  -0.4380  -0.0026   0.3756   4.3049  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)   0.1857     0.1100   1.689   0.0912 .  
## RC1          -4.1619     0.3364 -12.372   <2e-16 ***
## RC2          -2.2199     0.2550  -8.704   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1283.43  on 925  degrees of freedom
## Residual deviance:  547.78  on 923  degrees of freedom
## AIC: 553.78
## 
## Number of Fisher Scoring iterations: 7
\end{verbatim}

The p-values presented in the table above are all less than 0.05,
indicating that the third model fits well and that the first three
variables are the most important factors influencing the goodness of the
fit.

\end{document}
